# Generated by Django 2.1.7 on 2019-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('mean', models.DecimalField(decimal_places=2, max_digits=4)),
                ('median', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mode', models.DecimalField(decimal_places=2, max_digits=4)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
