# Generated by Django 2.1.7 on 2019-08-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemodel',
            name='imagetype',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
    ]
