# Generated by Django 2.1.7 on 2019-08-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0003_auto_20190818_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framemodel',
            name='mean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='framemodel',
            name='median',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='framemodel',
            name='mode',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='framemodel',
            name='standard_deviation',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
