# Generated by Django 2.1.7 on 2019-08-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0004_auto_20190818_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framemodel',
            name='mode',
        ),
    ]
