# Generated by Django 2.1.7 on 2019-08-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0005_remove_framemodel_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framemodel',
            old_name='image',
            new_name='depth_image',
        ),
        migrations.RenameField(
            model_name='framemodel',
            old_name='imagetype',
            new_name='image_type',
        ),
        migrations.AddField(
            model_name='framemodel',
            name='normal_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='framemodel',
            name='processed_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
