# Generated by Django 2.1.7 on 2019-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0006_auto_20190818_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemodel',
            name='depth_image_loc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='framemodel',
            name='normal_image_loc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='framemodel',
            name='processed_image_loc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
